name: Ceres build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  release:
    types: [published, edited]
  workflow_dispatch:
  create:

jobs:
  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ["cp37-cp37m","cp38-cp38"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build for Linux
      run: |
        # must be run in docker, cannot be run as freestanding script for toolchain issues
        # run on old CentOS. but it's CentOS, so it's yum(RPM) not apt. very old glibc. glibc API is back-compatible but not forward. See https://github.com/pypa/manylinux
        # see https://github.com/varunagrawal/docker-images/blob/master/gtsam-manylinux/Dockerfile for an example
        # container, but it does not have some necesssary boost packages --> varunagrawal/gtsam-manylinux:latest
        sudo docker run --rm -e PLAT=manylinux2014_x86_64 -e PYTHON_VERSION=${{ matrix.pyversion }} -v `pwd`:/io quay.io/pypa/manylinux2014_x86_64 /io/package/build-linux.sh ${{ matrix.pyversion }}
        # cleanup for custom runner
        sudo chown -R $(whoami):$(whoami) .

